use_frameworks!

platform :ios, '9.3'

target 'ClubKit_Example' do
  pod 'SKTCapture', '~>1.2'
  pod 'RealmSwift', '~>5.4'
  pod 'ClubKit', :path => '../'

  target 'ClubKit_Tests' do
    inherit! :search_paths

    
  end
end
